// Team Conference Mappings (Auto-generated from CBB Data API)
// DO NOT EDIT MANUALLY - Run fetch_conferences_from_api.py to update

const teamConferences = {
    'abilene christian': 'WAC',
    'air force': 'Mountain West',
    'akron': 'MAC',
    'alabama': 'SEC',
    'alabama a&m': 'SWAC',
    'alabama state': 'SWAC',
    'alcorn state': 'SWAC',
    'american university': 'Patriot',
    'app state': 'Sun Belt',
    'arizona': 'Big 12',
    'arizona state': 'Big 12',
    'arkansas': 'SEC',
    'arkansas state': 'Sun Belt',
    'arkansas-pine bluff': 'SWAC',
    'army': 'Patriot',
    'auburn': 'SEC',
    'austin peay': 'ASUN',
    'byu': 'Big 12',
    'ball state': 'MAC',
    'baylor': 'Big 12',
    'bellarmine': 'ASUN',
    'belmont': 'MVC',
    'bethune-cookman': 'SWAC',
    'binghamton': 'Am. East',
    'boise state': 'Mountain West',
    'boston college': 'ACC',
    'boston university': 'Patriot',
    'bowling green': 'MAC',
    'bradley': 'MVC',
    'brown': 'Ivy',
    'bryant': 'Am. East',
    'bucknell': 'Patriot',
    'buffalo': 'MAC',
    'butler': 'Big East',
    'cal poly': 'Big West',
    'cal state bakersfield': 'Big West',
    'cal state fullerton': 'Big West',
    'cal state northridge': 'Big West',
    'california': 'ACC',
    'california baptist': 'WAC',
    'campbell': 'CAA',
    'canisius': 'MAAC',
    'central arkansas': 'ASUN',
    'central connecticut': 'NEC',
    'central michigan': 'MAC',
    'charleston': 'CAA',
    'charleston southern': 'Big South',
    'charlotte': 'American',
    'chattanooga': 'SoCon',
    'chicago state': 'NEC',
    'cincinnati': 'Big 12',
    'clemson': 'ACC',
    'cleveland state': 'Horizon',
    'coastal carolina': 'Sun Belt',
    'colgate': 'Patriot',
    'colorado': 'Big 12',
    'colorado state': 'Mountain West',
    'columbia': 'Ivy',
    'coppin state': 'MEAC',
    'cornell': 'Ivy',
    'creighton': 'Big East',
    'dartmouth': 'Ivy',
    'davidson': 'A-10',
    'dayton': 'A-10',
    'depaul': 'Big East',
    'delaware': 'CUSA',
    'delaware state': 'MEAC',
    'denver': 'Summit',
    'detroit mercy': 'Horizon',
    'drake': 'MVC',
    'drexel': 'CAA',
    'duke': 'ACC',
    'duquesne': 'A-10',
    'east carolina': 'American',
    'east tennessee state': 'SoCon',
    'east texas a&m': 'Southland',
    'eastern illinois': 'OVC',
    'eastern kentucky': 'ASUN',
    'eastern michigan': 'MAC',
    'eastern washington': 'Big Sky',
    'elon': 'CAA',
    'evansville': 'MVC',
    'fairfield': 'MAAC',
    'fairleigh dickinson': 'NEC',
    'florida': 'SEC',
    'florida a&m': 'SWAC',
    'florida atlantic': 'American',
    'florida gulf coast': 'ASUN',
    'florida international': 'CUSA',
    'florida state': 'ACC',
    'fordham': 'A-10',
    'fresno state': 'Mountain West',
    'furman': 'SoCon',
    'gardner-webb': 'Big South',
    'george mason': 'A-10',
    'george washington': 'A-10',
    'georgetown': 'Big East',
    'georgia': 'SEC',
    'georgia southern': 'Sun Belt',
    'georgia state': 'Sun Belt',
    'georgia tech': 'ACC',
    'gonzaga': 'WCC',
    'grambling': 'SWAC',
    'grand canyon': 'Mountain West',
    'green bay': 'Horizon',
    'hampton': 'CAA',
    'harvard': 'Ivy',
    "hawai'i": 'Big West',
    'high point': 'Big South',
    'hofstra': 'CAA',
    'holy cross': 'Patriot',
    'houston': 'Big 12',
    'houston christian': 'Southland',
    'howard': 'MEAC',
    'iu indianapolis': 'Horizon',
    'idaho': 'Big Sky',
    'idaho state': 'Big Sky',
    'illinois': 'Big Ten',
    'illinois state': 'MVC',
    'incarnate word': 'Southland',
    'indiana': 'Big Ten',
    'indiana state': 'MVC',
    'iona': 'MAAC',
    'iowa': 'Big Ten',
    'iowa state': 'Big 12',
    'jackson state': 'SWAC',
    'jacksonville': 'ASUN',
    'jacksonville state': 'CUSA',
    'james madison': 'Sun Belt',
    'kansas': 'Big 12',
    'kansas city': 'Summit',
    'kansas state': 'Big 12',
    'kennesaw state': 'CUSA',
    'kent state': 'MAC',
    'kentucky': 'SEC',
    'lsu': 'SEC',
    'la salle': 'A-10',
    'lafayette': 'Patriot',
    'lamar': 'Southland',
    'le moyne': 'NEC',
    'lehigh': 'Patriot',
    'liberty': 'CUSA',
    'lindenwood': 'OVC',
    'lipscomb': 'ASUN',
    'little rock': 'OVC',
    'long beach state': 'Big West',
    'long island university': 'NEC',
    'longwood': 'Big South',
    'louisiana': 'Sun Belt',
    'louisiana tech': 'CUSA',
    'louisville': 'ACC',
    'loyola chicago': 'A-10',
    'loyola maryland': 'Patriot',
    'loyola marymount': 'WCC',
    'maine': 'Am. East',
    'manhattan': 'MAAC',
    'marist': 'MAAC',
    'marquette': 'Big East',
    'marshall': 'Sun Belt',
    'maryland': 'Big Ten',
    'maryland eastern shore': 'MEAC',
    'massachusetts': 'MAC',
    'mcneese': 'Southland',
    'memphis': 'American',
    'mercer': 'SoCon',
    'mercyhurst': 'NEC',
    'merrimack': 'MAAC',
    'miami': 'ACC',
    'miami (oh)': 'MAC',
    'michigan': 'Big Ten',
    'michigan state': 'Big Ten',
    'middle tennessee': 'CUSA',
    'milwaukee': 'Horizon',
    'minnesota': 'Big Ten',
    'mississippi state': 'SEC',
    'mississippi valley state': 'SWAC',
    'missouri': 'SEC',
    'missouri state': 'CUSA',
    'monmouth': 'CAA',
    'montana': 'Big Sky',
    'montana state': 'Big Sky',
    'morehead state': 'OVC',
    'morgan state': 'MEAC',
    "mount st. mary's": 'MAAC',
    'murray state': 'MVC',
    'nc state': 'ACC',
    'njit': 'Am. East',
    'navy': 'Patriot',
    'nebraska': 'Big Ten',
    'nevada': 'Mountain West',
    'new hampshire': 'Am. East',
    'new haven': 'NEC',
    'new mexico': 'Mountain West',
    'new mexico state': 'CUSA',
    'new orleans': 'Southland',
    'niagara': 'MAAC',
    'nicholls': 'Southland',
    'norfolk state': 'MEAC',
    'north alabama': 'ASUN',
    'north carolina': 'ACC',
    'north carolina a&t': 'CAA',
    'north carolina central': 'MEAC',
    'north dakota': 'Summit',
    'north dakota state': 'Summit',
    'north florida': 'ASUN',
    'north texas': 'American',
    'northeastern': 'CAA',
    'northern arizona': 'Big Sky',
    'northern colorado': 'Big Sky',
    'northern illinois': 'MAC',
    'northern iowa': 'MVC',
    'northern kentucky': 'Horizon',
    'northwestern': 'Big Ten',
    'northwestern state': 'Southland',
    'notre dame': 'ACC',
    'oakland': 'Horizon',
    'ohio': 'MAC',
    'ohio state': 'Big Ten',
    'oklahoma': 'SEC',
    'oklahoma state': 'Big 12',
    'old dominion': 'Sun Belt',
    'ole miss': 'SEC',
    'omaha': 'Summit',
    'oral roberts': 'Summit',
    'oregon': 'Big Ten',
    'oregon state': 'WCC',
    'pacific': 'WCC',
    'penn state': 'Big Ten',
    'pennsylvania': 'Ivy',
    'pepperdine': 'WCC',
    'pittsburgh': 'ACC',
    'portland': 'WCC',
    'portland state': 'Big Sky',
    'prairie view a&m': 'SWAC',
    'presbyterian': 'Big South',
    'princeton': 'Ivy',
    'providence': 'Big East',
    'purdue': 'Big Ten',
    'purdue fort wayne': 'Horizon',
    'queens university': 'ASUN',
    'quinnipiac': 'MAAC',
    'radford': 'Big South',
    'rhode island': 'A-10',
    'rice': 'American',
    'richmond': 'A-10',
    'rider': 'MAAC',
    'robert morris': 'Horizon',
    'rutgers': 'Big Ten',
    'se louisiana': 'Southland',
    'siu edwardsville': 'OVC',
    'smu': 'ACC',
    'sacramento state': 'Big Sky',
    'sacred heart': 'MAAC',
    "saint joseph's": 'A-10',
    'saint louis': 'A-10',
    "saint mary's": 'WCC',
    "saint peter's": 'MAAC',
    'sam houston': 'CUSA',
    'samford': 'SoCon',
    'san diego': 'WCC',
    'san diego state': 'Mountain West',
    'san francisco': 'WCC',
    'san josé state': 'Mountain West',
    'santa clara': 'WCC',
    'seattle u': 'WCC',
    'seton hall': 'Big East',
    'siena': 'MAAC',
    'south alabama': 'Sun Belt',
    'south carolina': 'SEC',
    'south carolina state': 'MEAC',
    'south carolina upstate': 'Big South',
    'south dakota': 'Summit',
    'south dakota state': 'Summit',
    'south florida': 'American',
    'southeast missouri state': 'OVC',
    'southern': 'SWAC',
    'southern illinois': 'MVC',
    'southern indiana': 'OVC',
    'southern miss': 'Sun Belt',
    'southern utah': 'WAC',
    'st. bonaventure': 'A-10',
    'st. francis (pa)': 'NEC',
    "st. john's": 'Big East',
    'st. thomas-minnesota': 'Summit',
    'stanford': 'ACC',
    'stephen f. austin': 'Southland',
    'stetson': 'ASUN',
    'stonehill': 'NEC',
    'stony brook': 'CAA',
    'syracuse': 'ACC',
    'tcu': 'Big 12',
    'tarleton state': 'WAC',
    'temple': 'American',
    'tennessee': 'SEC',
    'tennessee state': 'OVC',
    'tennessee tech': 'OVC',
    'texas': 'SEC',
    'texas a&m': 'SEC',
    'texas a&m-corpus christi': 'Southland',
    'texas southern': 'SWAC',
    'texas state': 'Sun Belt',
    'texas tech': 'Big 12',
    'the citadel': 'SoCon',
    'toledo': 'MAC',
    'towson': 'CAA',
    'troy': 'Sun Belt',
    'tulane': 'American',
    'tulsa': 'American',
    'uab': 'American',
    'ualbany': 'Am. East',
    'uc davis': 'Big West',
    'uc irvine': 'Big West',
    'uc riverside': 'Big West',
    'uc san diego': 'Big West',
    'uc santa barbara': 'Big West',
    'ucf': 'Big 12',
    'ucla': 'Big Ten',
    'uconn': 'Big East',
    'uic': 'MVC',
    'ul monroe': 'Sun Belt',
    'umbc': 'Am. East',
    'umass lowell': 'Am. East',
    'unc asheville': 'Big South',
    'unc greensboro': 'SoCon',
    'unc wilmington': 'CAA',
    'unlv': 'Mountain West',
    'usc': 'Big Ten',
    'ut arlington': 'WAC',
    'ut martin': 'OVC',
    'ut rio grande valley': 'Southland',
    'utep': 'CUSA',
    'utsa': 'American',
    'utah': 'Big 12',
    'utah state': 'Mountain West',
    'utah tech': 'WAC',
    'utah valley': 'WAC',
    'vcu': 'A-10',
    'vmi': 'SoCon',
    'valparaiso': 'MVC',
    'vanderbilt': 'SEC',
    'vermont': 'Am. East',
    'villanova': 'Big East',
    'virginia': 'ACC',
    'virginia tech': 'ACC',
    'wagner': 'NEC',
    'wake forest': 'ACC',
    'washington': 'Big Ten',
    'washington state': 'WCC',
    'weber state': 'Big Sky',
    'west georgia': 'ASUN',
    'west virginia': 'Big 12',
    'western carolina': 'SoCon',
    'western illinois': 'OVC',
    'western kentucky': 'CUSA',
    'western michigan': 'MAC',
    'wichita state': 'American',
    'william & mary': 'CAA',
    'winthrop': 'Big South',
    'wisconsin': 'Big Ten',
    'wofford': 'SoCon',
    'wright state': 'Horizon',
    'wyoming': 'Mountain West',
    'xavier': 'Big East',
    'yale': 'Ivy',
    'youngstown state': 'Horizon',
};

const allConferences = [
    'A-10',
    'ACC',
    'ASUN',
    'Am. East',
    'American',
    'Big 12',
    'Big East',
    'Big Sky',
    'Big South',
    'Big Ten',
    'Big West',
    'CAA',
    'CUSA',
    'Horizon',
    'Ivy',
    'MAAC',
    'MAC',
    'MEAC',
    'MVC',
    'Mountain West',
    'NEC',
    'OVC',
    'Patriot',
    'SEC',
    'SWAC',
    'SoCon',
    'Southland',
    'Summit',
    'Sun Belt',
    'WAC',
    'WCC',
];
